=== GershonLab/MTBfx/JSONschema/taskData_schemaIntInt.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://github.com/akaat/MTBfx/blob/K1off/JSONschema/taskData_schemaIntInt.json",
  "title": "Response=Int Score=Int Schema",
  "description": "This schema includes all elements for MTB measures that follows a response=integer score=integer data type. It has required elements common to all measures, and optional elements related to the dichotomous CAT engine. Note that it frequently references the external sharedSchema.json file for definitions.",
  "type": "object",
  "properties":{
    "testVersion": {"$ref": "sharedSchema.json#/definitions/testVersion"},
    "taskStatus": {"$ref": "sharedSchema.json#/definitions/taskStatus"},
    "locale": {"$ref": "sharedSchema.json#/definitions/locale"},
    "startDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
    "endDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
    "taskRunUUID": {"$ref": "sharedSchema.json#/definitions/taskRunUUID"},
    "userInteractions": {"$ref": "sharedSchema.json#/definitions/userInteractions"},
    "schemaIdentifier": {"$ref": "sharedSchema.json#/definitions/schemaIdentifier"},
    "consideredSteps": {"$ref": "sharedSchema.json#/definitions/consideredSteps"},
    "administeredSteps": {"$ref": "sharedSchema.json#/definitions/administeredSteps"},
    "scores": {"$ref": "sharedSchema.json#/definitions/scores"},
    "type":{
      "type": "string",
      "description": "The serialization for this task"
	  },
	  "taskName": {
	    "type": "string",
	    "description": "This is the test/task name as administered. It will be automatically provided as part of metadata and as such is not enumerated herein"
	  },
	  "steps": {
	    "type": "array",
	    "description": "This records all of the items/steps administered during this assessment. It records the response and score",
	    "additionalItems": false,
	    "items":{
	      "oneOf":[
	        {
	          "type": "object",
	          "description": "A record for each item administered in this assessment using the standard item selection engine.",
	          "properties":{
	            "type":{
	              "type": "string",
	              "description": "The type of result this is",
	              "examples":["spellingStepresult","mfsStepResult","mssStepResult"]
	            },
	            "identifier": {"$ref": "sharedSchema.json#/definitions/stepIdentifier"},
	            "startDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
	            "endDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
	            "practice": {"$ref": "sharedSchema.json#/definitions/practice"},
	            "instruction": {"$ref": "sharedSchema.json#/definitions/instructions"},
	            "wasInterrupted": {"$ref": "sharedSchema.json#/definitions/wasInterrupted"},
	            "score": {"$ref": "sharedSchema.json#/definitions/itemScore"},
	            "responseTime": {"$ref": "sharedSchema.json#/definitions/responseTime"},
	            "position":{
	              "type": "integer",
	              "minimum": 1,
	              "description": "The order of screen/step progression for this administration"
	            },
	            "response": {
	              "type": "integer",
	              "description": "This is the int-int schema, whereby the response is a string and the score is an integer. Often this is the position on the screen for a response. With current measures, it is limited to 0 to 18, which is wider than most tasks need but should adequately cover all current measures.",
	              "minimum": 0,
	              "maximum": 26
	            },
	            "failRuleSection":{
	              "type": "string",
	              "description": "This is a one-off field for monitoring failing practice, used by DCCS only"
	            },
	            "stepGroup":{
	              "type": "string",
	              "description": "an indicator for if this is the first or second half of the Flanker measure - only appicable to it"
	            },
	            "anticipationError":{
	              "type": "integer",
	              "default": 0,
	              "maximum": 5,
	              "description": "This is used in the Flanker test to indicate if an anticipation error occurred during this screen"
	            },
	            "section": {
	              "type" : "string",
	              "description" : "this is used by FNAME Test to indicate what portion of the test this item comes from. This is auto-populated by the test and therefore not enumerated herein, though it can only take 3 options"
	            },
	            "didTimeout": {
	              "type": "boolean",
	              "default": false,
	              "description": "An indicator for PSM as to whether the measure timed out before it was finished"
	            },
	            "sequenceNumber":{
	              "type": "integer",
	              "minimum": 1,
	              "maximum": 2,
	              "description": "This is used by PSM to indicate if it is the first time or the second time a person is taking the trial."
	            },
	            "exactMatchScoreName":{
	              "type":"string",
	              "description": "Used in PSM as an indicator for whether the picture in this step contributes to exactMatch1 or exactMatch2."
	            },
	            "adjacentPairScoreName":{
	              "type":"string",
	              "description": "Used in PSM as an indicator for whether the picture in this step contributes to adjacentPairs1 or adjacentPairs2."
	            },
	            "parentStepIdentifier": {"$ref": "sharedSchema.json#/definitions/stepIdentifier"}
	          },
	          "additionalProperties": false,
	          "required": ["type","identifier","startDate","endDate","position"]
	        },
	        {
	          "type": "object",
	          "description": "A record for each item administered in this assessment using the dichotomous engine.",
	          "properties":{
	            "type":{
	              "type": "string",
	              "description": "The type of result this is",
	              "examples":["spellingStepresult","mfsStepResult","mssStepResult"]
	            },
	            "identifier": {
	              "type": "string",
	              "description": "This is the stepID, and should be redundant with `stepIdentifier` used in  `userInteractions` and the `identifier` used in `stepHistory` elements."
	            },
	            "startDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
	            "endDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
	            "practice": {"$ref": "sharedSchema.json#/definitions/practice"},
	            "instruction": {"$ref": "sharedSchema.json#/definitions/instructions"},
	            "wasInterrupted": {"$ref": "sharedSchema.json#/definitions/wasInterrupted"},
	            "score": {"$ref": "sharedSchema.json#/definitions/itemScore"},
	            "responseTime": {"$ref": "sharedSchema.json#/definitions/responseTime"},
	            "position":{
	              "type": "integer",
	              "minimum": 1,
	              "description": "The order of screen/step progression for this administration"
	            },
	            "response": {
	              "type": "integer",
	              "description": "This is the int-int schema, whereby the response is a string and the score is an integer. Often this is the position on the screen for a response. With current measures, it is limited to 0 to 18, which is wider than most tasks need but should adequately cover all current measures.",
	              "minimum": 0,
	              "maximum": 26
	            },
	            "failRuleSection":{
	              "type": "string",
	              "description": "This is a one-off field for monitoring failing practice, used by DCCS only"
	            },
	            "theta":{
	              "type": "number",
	              "default": 0,
	              "description": "This is the theta value AFTER administering this step."
	            },
	            "se":{
	              "type": "number",
	              "description": "This is the standard error associated with the theta estimate AFTER administering this step. The default value is the starting value that initializes the dichotomous engine. It must be positive.",
	              "default": 99,
	              "minimum": 0.0
	            }
	          },
	          "additionalProperties": false,
	          "required": ["type","identifier","startDate","endDate","practice","wasInterrupted","position", "theta","se"]
	        }
	      ]
	    }
	  },
	  "stepHistory": {
	    "type": "array",
	    "description": "This records all of the items/steps administered presented or considered during this assessment. It records the response and score if an examinee got to that point; it also records items that may not have been completed, e.g. due to an interruption. It is identical to or a superset of the `steps` field.",
	    "additionalItems": false,
	    "items":{
	      "oneOf":[
	        {
	          "type": "object",
	          "description": "A record for each item administered in this assessment using the standard item selection engine.",
	          "properties":{
	            "type":{
	              "type": "string",
	              "description": "The type of result this is",
	              "examples":["spellingStepresult","mfsStepResult","mssStepResult"]
	            },
	            "identifier": {"$ref": "sharedSchema.json#/definitions/stepIdentifier"},
	            "startDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
	            "endDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
	            "practice": {"$ref": "sharedSchema.json#/definitions/practice"},
	            "instruction": {"$ref": "sharedSchema.json#/definitions/instructions"},
	            "wasInterrupted": {"$ref": "sharedSchema.json#/definitions/wasInterrupted"},
	            "score": {"$ref": "sharedSchema.json#/definitions/itemScore"},
	            "responseTime": {"$ref": "sharedSchema.json#/definitions/responseTime"},
	            "position":{
	              "type": "integer",
	              "minimum": 1,
	              "description": "The order of screen/step progression for this administration"
	            },
	            "response": {
	              "type": "integer",
	              "description": "This is the int-int schema, whereby the response is a string and the score is an integer. Often this is the position on the screen for a response. With current measures, it is limited to 0 to 18, which is wider than most tasks need but should adequately cover all current measures.",
	              "minimum": 0,
	              "maximum": 26
	            },
	            "failRuleSection":{
	              "type": "string",
	              "description": "This is a one-off field for monitoring failing practice, used by DCCS only"
	            },
	            "stepGroup":{
	              "type": "string",
	              "description": "an indicator for if this is the first or second half of the Flanker measure - only appicable to it"
	            },
	            "anticipationError":{
	              "type": "integer",
	              "default": 0,
	              "maximum": 5,
	              "description": "This is used in the Flanker test to indicate if an anticipation error occurred during this screen"
	            },
	            "section": {
	              "type" : "string",
	              "description" : "this is used by FNAME Test to indicate what portion of the test this item comes from. This is auto-populated by the test and therefore not enumerated herein, though it can only take 3 options"
	            },
	            "didTimeout": {
	              "type": "boolean",
	              "default": false,
	              "description": "An indicator for PSM as to whether the measure timed out before it was finished"
	            },
	            "sequenceNumber":{
	              "type": "integer",
	              "minimum": 1,
	              "maximum": 2,
	              "description": "This is used by PSM to indicate if it is the first time or the second time a person is taking the trial."
	            },
	            "exactMatchScoreName":{
	              "type":"string",
	              "description": "Used in PSM as an indicator for whether the picture in this step contributes to exactMatch1 or exactMatch2."
	            },
	            "adjacentPairScoreName":{
	              "type":"string",
	              "description": "Used in PSM as an indicator for whether the picture in this step contributes to adjacentPairs1 or adjacentPairs2."
	            },
	            "parentStepIdentifier": {"$ref": "sharedSchema.json#/definitions/stepIdentifier"}
	          },
	          "additionalProperties": false,
	          "required": ["type","identifier","startDate","endDate"]
	        },
	        {
	          "type": "object",
	          "description": "A record for each item administered in this assessment using the dichotomous engine.",
	          "properties":{
	            "type":{
	              "type": "string",
	              "description": "The type of result this is",
	              "examples":["spellingStepresult","mfsStepResult","mssStepResult"]
	            },
	            "identifier": {
	              "type": "string",
	              "description": "This is the stepID, and should be redundant with `stepIdentifier` used in  `userInteractions` and the `identifier` used in `stepHistory` elements."
	            },
	            "startDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
	            "endDate": {"$ref": "sharedSchema.json#/definitions/timemarks"},
	            "practice": {"$ref": "sharedSchema.json#/definitions/practice"},
	            "instruction": {"$ref": "sharedSchema.json#/definitions/instructions"},
	            "wasInterrupted": {"$ref": "sharedSchema.json#/definitions/wasInterrupted"},
	            "score": {"$ref": "sharedSchema.json#/definitions/itemScore"},
	            "responseTime": {"$ref": "sharedSchema.json#/definitions/responseTime"},
	            "position":{
	              "type": "integer",
	              "minimum": 1,
	              "description": "The order of screen/step progression for this administration"
	            },
	            "response": {
	              "type": "integer",
	              "description": "This is the int-int schema, whereby the response is a string and the score is an integer. Often this is the position on the screen for a response. With current measures, it is limited to 0 to 18, which is wider than most tasks need but should adequately cover all current measures.",
	              "minimum": 0,
	              "maximum": 26
	            },
	            "failRuleSection":{
	              "type": "string",
	              "description": "This is a one-off field for monitoring failing practice, used by DCCS only"
	            },
	            "theta":{
	              "type": "number",
	              "default": 0,
	              "description": "This is the theta value AFTER administering this step."
	            },
	            "se":{
	              "type": "number",
	              "description": "This is the standard error associated with the theta estimate AFTER administering this step. The default value is the starting value that initializes the dichotomous engine. It must be positive.",
	              "default": 99,
	              "minimum": 0.0
	            }
	          },
	          "additionalProperties": false,
	          "required": ["type","identifier","startDate","endDate","practice","wasInterrupted","theta","se"]
	        }
	      ]
	    }
	  }
  },
  "additionalProperties": true,
  "$comment": "The additionalProperties element is currently true to allow for the dichotomous engine additional elements, but will be changed in future versions.",
  "required": ["steps","testVersion","userInteractions","taskStatus","startDate","endDate","stepHistory","schemaIdentifier"]
}

=== GershonLab/MTBfx/JSONschema/June22 revision/Initial taskData/testData Flanker Android (1.4.163).json
{
  "steps": [
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "I_0",
      "position": 1,
      "startDate": "2022-05-24T16:54:15.351-05:00",
      "endDate": "2022-05-24T16:54:19.696-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "I_1",
      "position": 2,
      "startDate": "2022-05-24T16:54:19.706-05:00",
      "endDate": "2022-05-24T16:54:22.458-05:00",
      "response": 2
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "I_2",
      "position": 3,
      "startDate": "2022-05-24T16:54:22.461-05:00",
      "endDate": "2022-05-24T16:54:23.548-05:00",
      "response": 2
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "I_3",
      "position": 4,
      "startDate": "2022-05-24T16:54:23.551-05:00",
      "endDate": "2022-05-24T16:54:25.296-05:00",
      "response": 2
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "T_1I",
      "position": 5,
      "startDate": "2022-05-24T16:54:25.300-05:00",
      "endDate": "2022-05-24T16:54:29.053-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_1a",
      "position": 6,
      "startDate": "2022-05-24T16:54:29.060-05:00",
      "endDate": "2022-05-24T16:54:30.342-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_1b",
      "position": 7,
      "startDate": "2022-05-24T16:54:30.346-05:00",
      "endDate": "2022-05-24T16:54:30.447-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_1c",
      "position": 8,
      "startDate": "2022-05-24T16:54:30.452-05:00",
      "endDate": "2022-05-24T16:54:35.326-05:00",
      "practice": true,
      "response": 2,
      "score": 1,
      "responseTime": 2406
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_2a",
      "position": 9,
      "startDate": "2022-05-24T16:54:35.333-05:00",
      "endDate": "2022-05-24T16:54:36.600-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_2b",
      "position": 10,
      "startDate": "2022-05-24T16:54:36.602-05:00",
      "endDate": "2022-05-24T16:54:36.703-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_2c",
      "position": 11,
      "startDate": "2022-05-24T16:54:36.704-05:00",
      "endDate": "2022-05-24T16:54:39.628-05:00",
      "practice": true,
      "response": 1,
      "score": 1,
      "responseTime": 527
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_3a",
      "position": 12,
      "startDate": "2022-05-24T16:54:46.458-05:00",
      "endDate": "2022-05-24T16:54:48.974-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_3b",
      "position": 13,
      "startDate": "2022-05-24T16:54:48.979-05:00",
      "endDate": "2022-05-24T16:54:49.082-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_3c",
      "position": 14,
      "startDate": "2022-05-24T16:54:49.085-05:00",
      "endDate": "2022-05-24T16:54:52.372-05:00",
      "practice": true,
      "response": 2,
      "score": 1,
      "responseTime": 1008
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_4a",
      "position": 15,
      "startDate": "2022-05-24T16:54:52.380-05:00",
      "endDate": "2022-05-24T16:54:52.906-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_4b",
      "position": 16,
      "startDate": "2022-05-24T16:54:52.911-05:00",
      "endDate": "2022-05-24T16:54:53.013-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_4c",
      "position": 17,
      "startDate": "2022-05-24T16:54:53.017-05:00",
      "endDate": "2022-05-24T16:54:55.903-05:00",
      "practice": true,
      "response": 2,
      "score": 1,
      "responseTime": 560
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_5a",
      "position": 18,
      "startDate": "2022-05-24T16:54:55.911-05:00",
      "endDate": "2022-05-24T16:54:57.179-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_5b",
      "position": 19,
      "startDate": "2022-05-24T16:54:57.184-05:00",
      "endDate": "2022-05-24T16:54:57.287-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "P_5c",
      "position": 20,
      "startDate": "2022-05-24T16:54:57.290-05:00",
      "endDate": "2022-05-24T16:55:00.136-05:00",
      "practice": true,
      "response": 1,
      "score": 1,
      "responseTime": 685
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "T_2L",
      "position": 21,
      "startDate": "2022-05-24T16:55:00.144-05:00",
      "endDate": "2022-05-24T16:55:01.192-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A01a",
      "position": 22,
      "startDate": "2022-05-24T16:55:01.203-05:00",
      "endDate": "2022-05-24T16:55:02.472-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A01b",
      "position": 23,
      "startDate": "2022-05-24T16:55:02.476-05:00",
      "endDate": "2022-05-24T16:55:02.578-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A01c",
      "position": 24,
      "startDate": "2022-05-24T16:55:02.582-05:00",
      "endDate": "2022-05-24T16:55:03.481-05:00",
      "response": 1,
      "score": 1,
      "responseTime": 577
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A02a",
      "position": 25,
      "startDate": "2022-05-24T16:55:03.489-05:00",
      "endDate": "2022-05-24T16:55:04.010-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A02b",
      "position": 26,
      "startDate": "2022-05-24T16:55:04.012-05:00",
      "endDate": "2022-05-24T16:55:04.113-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A02c",
      "position": 27,
      "startDate": "2022-05-24T16:55:04.115-05:00",
      "endDate": "2022-05-24T16:55:04.896-05:00",
      "response": 2,
      "score": 1,
      "responseTime": 486
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A03a",
      "position": 28,
      "startDate": "2022-05-24T16:55:04.904-05:00",
      "endDate": "2022-05-24T16:55:05.428-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A03b",
      "position": 29,
      "startDate": "2022-05-24T16:55:05.430-05:00",
      "endDate": "2022-05-24T16:55:05.532-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A03c",
      "position": 30,
      "startDate": "2022-05-24T16:55:05.536-05:00",
      "endDate": "2022-05-24T16:55:06.439-05:00",
      "response": 1,
      "score": 1,
      "responseTime": 595
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A04a",
      "position": 31,
      "startDate": "2022-05-24T16:55:06.447-05:00",
      "endDate": "2022-05-24T16:55:06.973-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A04b",
      "position": 32,
      "startDate": "2022-05-24T16:55:06.976-05:00",
      "endDate": "2022-05-24T16:55:07.078-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A04c",
      "position": 33,
      "startDate": "2022-05-24T16:55:07.082-05:00",
      "endDate": "2022-05-24T16:55:07.894-05:00",
      "response": 2,
      "score": 1,
      "responseTime": 502
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A05a",
      "position": 34,
      "startDate": "2022-05-24T16:55:07.902-05:00",
      "endDate": "2022-05-24T16:55:09.170-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A05b",
      "position": 35,
      "startDate": "2022-05-24T16:55:09.177-05:00",
      "endDate": "2022-05-24T16:55:09.280-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A05c",
      "position": 36,
      "startDate": "2022-05-24T16:55:09.287-05:00",
      "endDate": "2022-05-24T16:55:10.419-05:00",
      "response": 1,
      "score": 0,
      "responseTime": 818
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A06a",
      "position": 37,
      "startDate": "2022-05-24T16:55:10.427-05:00",
      "endDate": "2022-05-24T16:55:10.954-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A06b",
      "position": 38,
      "startDate": "2022-05-24T16:55:10.958-05:00",
      "endDate": "2022-05-24T16:55:11.060-05:00"
    },
    {
      "type": "edu.northwestern.mobiletoolbox.common.data.MtbStepResult",
      "identifier": "A06c",
